### ISSUE TITLE
첫 회의 일정

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#1]
안녕하세요, 김동규 학부생님.

이번 학기 팀프로젝트를 함께 하게 된 김광일 학부생이라고 합니다.

첫 회의 일정을 잡고자 issue 생성했습니다.

**Comment by ehdrb01** [comment]
지금 가능합니다!

**Comment by pangil5634** [comment]
그러면 제가 zoom 링크 보내드릴게요.
