### ISSUE TITLE
5월 8일 월요일 1차 제출 전까지의 TodoList

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#10]
5월 8일 월요일 전까지 제출해야 하는 내용 중 해야 할 부분들을 모아봤습니다.

- [x] 함수로 구현할 기능에 대한 아이디어 진행하기 (CRUD, 파일I/O, 검색 기능, 이외의 함수 2개)
- [x] WIKI page 작성 
- [x] README 작성 (주제, 소개, 사진, 기능 설명, 개발환경 및 언어, 팀소개 및 팀원이 맡은 역할)
* WIKI 참고 : https://github.com/cart-savior/cart_savior/wiki
* README 참고 : (https://github.com/gomster96/CSEE-SelfCheck) / (https://github.com/TeamProject-2022OSS/miniProject)

<h1> Detail ToDoList </h1>

**함수로 구현할 기능에 대한 아이디어 진행하기 (CRUD, 파일I/O, 검색 기능, 이외의 함수 3개)**
- [x] 조회
- [x] 추가
- [x] 수정
- [x] 삭제
- [x] 검색 기능
- [x] 파일 저장
- [x] #11
- [x] 기능2
- [x] 기능3
- [x] 종료 (종료는 함수 개수에서 제외하여 총 8개)

**WIKI page 작성**
- [x] 전체적인 틀 고민
- [x] 실제로 WIKI에 작성

**README 작성 (주제, 소개, 사진, 기능 설명, 개발환경 및 언어, 팀소개 및 팀원이 맡은 역할)**
- [x] 전체적인 틀 고민
- [x] 실제로 README에 작성

**Comment by pangil5634** [comment]
README.md 파일 완료됐습니다.

확인 부탁드리고, 동규님 브랜치에서 git pull origin main 부탁드립니다!

**Comment by ehdrb01** [comment]
확인 완료했습니다!
