### ISSUE TITLE
main branch 수정 요청

### ISSUE THREAD

**Issue by ehdrb01** [2023OSSL-TeamProject/MiniProject#13]
main branch에 CRUD 부분을 2가지 파트로 분리해서 작성 해두었습니다.

KDG 브랜치에 push 해둔 상태이고 확인 하시고 나시면 merge해서 main update 하도록 하겠습니다.

**Comment by pangil5634** [comment]
네 확인했습니다. 제 local에도 pull 진행하였고, merge와 push 진행했습니다. 수고 많으셨습니다.!

**Comment by ehdrb01** [comment]
.
