### ISSUE TITLE
userCRUD main.c 적용

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#15]
안녕하세요 김동규 학우님.

구현된 userCRUD 기능을 main.c에 적용하여 구현하는 과정을 진행하려 합니다.

이 부분이 구현된 이후에 washerCRUD를 본격적으로 해보겠습니다.

<user에 대한 todo list>
- [x] User에 대한 조회, 추가, 수정, 삭제 기능을 main.c에 적용하기(menu 드리즌)
- [x] success_fail 등 함수 성공여부 판단 함수 구현하기

**Comment by pangil5634** [comment]
<img width="448" alt="image" src="https://github.com/2023OSSL-TeamProject/MiniProject/assets/54162245/7aad47ad-2c5a-43bc-a1ba-6b221a391ea7">

Q. 처음에 프로그램을 실행해줄 때에 ListInit을 해주는 이유가 궁금합니다.

**Comment by pangil5634** [comment]
전체 구현 완료했습니다. 확인 댓글 남겨주시면 close하겠습니다.

**Comment by ehdrb01** [comment]
확인 하였습니다.
