### ISSUE TITLE
커밋명 통일

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#16]
안녕하세요 김동규 학우님

커밋 log를 확인하다가 저희가 게획한 바와 조금 다르게 진행된 부분이 있어서 이슈 남깁니다.

커밋이 어떠한 사람이 작성했는지 명확히 구분하기 위해 정의해놓은 "git commit -m "KKI : 커밋명"에 대한 부분을 지금부터라도 진행해보면 좋을 것 같습니다.

까먹지 않으려고 노력해봐요!

**Comment by ehdrb01** [comment]
네 알겠습니다~!
