### ISSUE TITLE
washerShop 기능

### ISSUE THREAD

**Issue by ehdrb01** [2023OSSL-TeamProject/MiniProject#17]
washerShop 기능 부분에서 user 구조체와 함수 수정이 필요하다고 판단이 들어서 제가 금일 내로 데모 버전 만들어 놓겠습니다!

추후 제가 올려놓은 코드 확인 해보시고 수정할 부분 수정 해주시면 좋을 것 같습니다!

**Comment by pangil5634** [comment]
closed 처리해주셔도 괜찮을 것 같습니다!
