### ISSUE TITLE
코드 작성 예시

### ISSUE THREAD

**Issue by ehdrb01** [2023OSSL-TeamProject/MiniProject#18]
코드 작성하는 부분에 있어서 형태가 저랑 광일 학우님이랑 다른 부분이 있는 것 같습니다.

예를 들어, 
while(true) {
}
저는 이런식으로 작업을 하지만 광일 학우님은
while(true)
{
}
이런식으로 작업을 하는 것 같습니다!

일관성있게 보기 위해서 광일 학우님이 하시는 방식으로 작업 하도록 하겠습니다.

이슈 확인하시면 close 해주시면 감사드리겠습니다.

**Comment by pangil5634** [comment]
그 부분은 제 vscode의 extension에서 자동적으로 정렬해주는 부분입니다!

이렇게 진행해주신다면 감사합니다 ㅎㅎ
