### ISSUE TITLE
washerShop 기능 업데이트

### ISSUE THREAD

**Issue by ehdrb01** [2023OSSL-TeamProject/MiniProject#19]
washerShop 기능 작성 완료하였습니다.
main 브랜치에서 확인 해보실 수 있으실 겁니다!

추가적으로 user 부분에 세제와 섬유유연제 수량 넣어두었으니, washerCRUD 만드실 때 참고하셔서 만드시면 될 것 같습니다.

**Comment by pangil5634** [comment]
넵 확인했습니다!
