### ISSUE TITLE
주제 정하기

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#2]
개발하고 싶은 주제를 자유롭게 3가지 정도 준비해 오면 좋겠습니다.

**Comment by ehdrb01** [comment]
주제 선정 데드라인은 언제까지로 하면 좋을까요?
제 생각에는 차주 일요일까지 정하고 줌으로 미팅 한 번 진행하면 좋을 것 같습니다.

**Comment by pangil5634** [comment]
기획 및 설계가 월요일까지로 공지가 되어서요!

금일 중으로 주제 선정 및 데이터 정의와 10개 이상의 함수 정의를 진행해야 할 것 같아요.

그리고 주말 중으로 프로그램의 전제적인 틀 정도는 구현을 하고, 돌아오는 주부터 본격적으로 개발을 진행하면 어떨까 싶네요!

<b>

1. 팀별 주제 선정하기
예시) 아래 이외에도 자유롭게 정할 수 있음
CAFE 디저트 자판기
출퇴근 관리 시스템
스터디 카페! 이젠 어디서든 예약할 수 있어요
가계부 프로그램

2. 프로젝트 설계
CRUD 기능, 데이터 파일 저장/읽어오기, 검색 메뉴(종료메뉴 제외) 등 (총 메뉴 8개 이상)
구조체로 한 세트의 데이터 정의 및 10개 이상 함수 정의 및 개발
github의 issue를 이용 충분한 토론 후 기획하고 정의할 것
</b>

이 두 가지 부분을 이번 주 일요일까지 진행하면 어떨까 싶습니다!

**Comment by ehdrb01** [comment]
그러면 5/6(토)까지 이 issue에 주제 개인당 3개 올리고 주제 선정한 다음, 필요한 데이터와 함수를 5/7(일)까지 정해보면 좋을 것 같아요!

**Comment by ehdrb01** [comment]
일단 이전에 진행한 개인별 미니프로젝트 주제를 공유해보면 좋을 것 같습니다!

저는 한동대학교 주차관리 시스템을 주제로 미니프로젝트 진행 했었습니다.

**Comment by pangil5634** [comment]
저는 백신 예약 및 조회 시스템을 주제로 진행했었습니다!

오늘 중으로 주제 정해서 보내드릴게요.

**Comment by ehdrb01** [comment]
주제 1: 세탁기 사용 프로그램(기숙사 내부 세탁기)
 - 제한된 세탁기 수량으로 인한 불편함 발생
주제 2: 자치회 물품 대여 시스템
 - 현재 네이버 예약으로 진행하는 것이 불편함이 있을 수 있다고 판단
주제 3: 공동 배달 시스템
 - 배달비 절약을 위함 학교 내부 공동 배달 시스템 어플 구축
 - 가게, 음식 종류 별로 카테고리 분류 후 사용할 수 있게 개발하면 좋을 것이라 판단

이렇게 3가지 주제 생각 해봤습니다!
주제 올려주시면 협의 후에 함수 정의 해보면 좋을 것 같아요!

**Comment by pangil5634** [comment]
* 주제 1 : 강의실 대여 시스템
* 주제 2 : 물건 판매 및 구매 시스템
* 주제 3 : 도서관 온라인 시스템

**Comment by ehdrb01** [comment]
이제 주제 선정 진행해보면 좋을 것 같은데, 제 생각에는 다른 주제들은 이미 다 있는 것들인 것 같아서 혹시 제가 낸 주제 1번 "세탁기 사용 프로그램" 이라는 주제로 팀 프로젝트 진행해보면 어떨까 싶어 의견 여쭤봅니다!

**Comment by pangil5634** [comment]
네 좋습니다! 해당 주제에 대해 논의해볼 issue를 생성해주셨더라구요. 거기서 한 번 논의해보죠
