### ISSUE TITLE
메뉴 드리즌 구현 완료

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#20]
안녕하세요 김동규 학우님.

지난 번에 구현해주셨던 washerShop과 이전에 구현해주셨던 userCRUD에 대한 전반적인 부분을 main.c와 연결시켜 메뉴 드리즌을 구현했습니다.

확실히 메뉴 드리즌에 연결 시켜놓지 않고 구현을 하게 되어 오류 발생이나 구현 여부에 대한 부분을 확인하기 어려운 점이 사실인 것 같습니다.

그러나 현재 메뉴 드리즌이 구현이 되었으니 앞으로 수정해 나가실 때 menu에서 바로바로 확인하실 수 있으실 겁니다. (보다 편리할 겁니다.)

수정된 부분은 commit 내용을 확인해주시는 것이 보다 빠를 것으로 예상 되며, pull 과정에서 conflict도 발생하곤 했지만 잘 해결했습니다.

확인해주시면 issue 닫겠습니다. 감사합니디.

**Comment by ehdrb01** [comment]
확인했습니다. 감사합니다!
