### ISSUE TITLE
앞으로의 일정

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#21]
안녕하세요 김동규 학우님.

userCRUD 구현 정말 고생 많으셨습니다. 

구현이 된 만큼 이제 washerCRUD를 구현해보려고 합니다.

지난 번 회의를 통해 말씀해주셨던 세부적인 부분과 아이디어를 결합하여 washerCRUD 기능 구현에 대한 내용은 새로운 issue로 작성해서 공유해드리겠습니다.

현재 보시는 issue에서는 구현 일정 공유를 말씀 드리기 위함입니다.

저희가 다음 주 월요일에 제출인 만큼 고려했을 때 아래와 같은 일정이 나왔습니다.

washerCRUD 구현 : 이번 주 수요일 23:00까지
전체 기능 테스트 및 수정 : 이번 주 금요일 23:00까지
WIKI 및 README final 정리 : 다음 주 월요일 18:00까지
최종 정리 : 다음 주 월요일 18:00 ~ 23:59까지

이제 일주일 채 남지 않은 기간 동안 파이팅해보면 좋겠습니다. 파이팅!

**Comment by ehdrb01** [comment]
확인했습니다 감사합니다!
