### ISSUE TITLE
WasherCRUD 기능 구현 계획

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#22]
안녕하세요 김동규 학우님.

지난 issue에 작성하여 공유해드린 바와 같이 WasherCRUD 기능 구현 계획에 대해서 정리 겸 공유해드리려고 합니다.

한동대학교의 기숙사는 총 8개입니다. 총 8개 기숙사 중에서 두 개의 기숙사만 선정하여 구현해보고자 합니다. (이후 보완하여 총 8개의 기숙사로 구현 가능성 존재) 
그 결과 비전관과 벧엘관으로 선정하였습니다. (비전 : 저 / 벧엘 : 동규님)

또한, 모든 기숙사는 총 4개의 층이 있다는 점과 각 층 별로 2개의 세탁기가 있다고 가정하고자 합니다.

세탁기에 대한 정보를 간략하게 정리하면 아래와 같습니다.

벧엘관 
1층 세탁기 1 / 세탁기 2
2층 세탁기 1 / 세탁기 2
3층 세탁기 1 / 세탁기 2
4층 세탁기 1 / 세탁기 2

비전관
1층 세탁기 1 / 세탁기 2
2층 세탁기 1 / 세탁기 2
3층 세탁기 1 / 세탁기 2
4층 세탁기 1 / 세탁기 2

이와 같은 flow로 세탁기를 선택하게 됩니다. 
세탁기를 선택한 이후에는 사용 가능한 시간을 통해 예약 시스템을 관리하고자 합니다. (세탁기 구동 가능 시간 : 08시~22시 [23시 이후는 침묵시간])

이제 가정이 이루어진 만큼 CRUD 별로 각각 설명 해드리겠습니다.

1) 조회
(1) 조회하고자 하는 기숙사, 층, 세탁기를 선정합니다
(2) 선정한 세탁기의 예약 시간표를 출력합니다.

2) 추가
(1) 예약하고자 하는 사용자의 학번을 입력합니다.
(2) 예약하고자 하는 기숙사, 층, 세탁기를 선정합니다.
(3) 선정한 세탁기의 예약 시간표를 출력합니다.
(4) 예약을 진행합니다. (원하는 시간대)
* 소지하고 있는 금액, 세제, 섬유유연제에 따라서 예약 성공 및 실패가 이루어집니다.
* 예약 성공 시 금액, 세제, 섬유유연제가 차감됩니다.
* 사용자 학번, 이름은 자동적으로 등록이 되며 세탁 예약에 추가됩니다.

3) 수정
(1) 예약을 수정하고자 하는 사용자의 학번을 입력한다.
* 예약 내역이 있는지 확인한다.
(2) 예약 내역 중 하나를 선택한다.
(3) 예약 내용을 수정한다. (시간대는 중복되지 않은 시간대에)

4) 삭제
(1) 예약을 삭제하고자 하는 사용자의 학번을 입력한다.
* 예약 내역이 있는지 확인한다.
(2) 예약 내역 중 하나를 선택한다.
(3) 예약 내용을 삭제한다.
* 삭제함으로써 금액, 세제, 섬유유연제가 반환된다.

최대한 열심히 해보겠습니다. 파이팅!

**Comment by pangil5634** [comment]
3번 수정을 제외한 모든 항목은 현재 구현이 완료된 상태입니다.

현재 코드 정리가 필요해보며 조금씩 보완해 나가려고 합니다.

파일I/O 부분과 관련해서 구현도 진행했습니다. 상당히 애를 먹었고,, 사실 밤샜습니다.

그래도 덕분에 많은 것을 배워갈 수 있어서 좋았습니다.

**Comment by ehdrb01** [comment]
고생하셨습니다!
