### ISSUE TITLE
washerShop 추가 기능

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#23]
안녕하세요 김동규 학우님!

구현해주신 washshop에 관해서 세제와 섬유유연제의 개수 현황도 볼 수 있는 내용이 추가되면 좋을 것 같아서 issue 남겨 드립니다!

금액 조회할 때 같이 조회하면 좋을 것 같습니다! 또한, 구매할 때에도 확인할 수 있으면 좋을 것 같습니다.

**Comment by pangil5634** [comment]
확인해주시는 comment과 구현해주신 뒤에 comment남겨주시면 감사하겠습니다!

**Comment by ehdrb01** [comment]
구현 완료 했습니다! 감사합니다!
