### ISSUE TITLE
다른 헤더파일의 구조체 참조 문제

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#24]
<img width="731" alt="image" src="https://github.com/2023OSSL-TeamProject/MiniProject/assets/54162245/d9fce414-c1b9-4fd8-bb00-1f24affd6947">

안녕하세요 김동규 학우님.

washerCRUD 작업 중에 해결되지 않는 문제가 있어서 공유해서 같이 해결하면 좋을 것 같아서 issue남깁니다.

사진과 같이 두 개의 구조체를 파라미터로 받는 WasherInsert 함수를 구현하던 중 오류가 발생했습니다.

inc/washerCRUD.h:18:38: error: unknown type name 'List'
int WasherInsert(Washer *washerList, List *list);
                                     ^
1 error generated.
make: *** [inc/washerCRUD.o] Error 1

와 같은 오류였고, 확인해본 결과 washerCRUD.h 에서 List로 정의된 구조체를 참조할 수 없는 문제였습니다.

즉 다른 헤더파일의 구조체를 참조하는 방식을 알아냈으면 합니다,,

**Comment by pangil5634** [comment]
위의 오류는 중복으로 헤더 파일을 포함시키는 문제로 보입니다. 동일한 헤더 파일이 중복으로 포함되어 구조체와 typedef가 중복 정의되고 있습니다. 이를 해결하기 위해서는 헤더 파일에 대한 중복 포함을 방지해야 합니다.

일반적으로 헤더 파일에서 중복 포함을 방지하기 위해 "#ifndef"과 "#define"으로 감싼 전처리기 지시문을 사용합니다. 이를 헤더 파일에 추가하여 중복 포함을 방지할 수 있습니다.

아래는 수정된 코드 예시입니다:

userCRUD.h:
```c
#ifndef USER_CRUD_H
#define USER_CRUD_H

typedef struct {
    // 구조체 내용
} User;

typedef struct {
    // 구조체 내용
} List;

// 함수 등의 선언

#endif
```

washerCRUD.h:
```c
#ifndef WASHER_CRUD_H
#define WASHER_CRUD_H

#include "userCRUD.h"

// washerCRUD.h의 나머지 내용

#endif
```

washerCRUD.c:
```c
#include "washerCRUD.h"

// washerCRUD.c의 나머지 내용
```

위의 코드에서는 `USER_CRUD_H`와 `WASHER_CRUD_H`와 같은 고유한 이름을 사용하여 각 헤더 파일을 전처리기 지시문으로 감싸고 있습니다. 이렇게 하면 중복 포함이 방지되고 오류가 해결될 것입니다.

이와 같이 수정한 후에는 중복 포함 오류가 사라지고, 코드가 정상적으로 컴파일되어 실행될 수 있습니다.

**Comment by pangil5634** [comment]
해결했습니다!

**Comment by ehdrb01** [comment]
감사합니다!
