### ISSUE TITLE
User file I/O 구현 관련

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#25]
안녕하세요 김동규 학우님

저희가 진행한 프로젝트의 상황을 점검해본 결과 'User'에 대한 File I/O을 구현해야 할 것 같아서 의견 남겨드립니다!

세탁기에 대한 File I/O는 구현이 된 상태이며, User에 대한 부분만 구현이 된다면 보다 완벽해져갈 것 같숩니다.

**Comment by ehdrb01** [comment]
앗 네 알겠습니다! 구현 해보도록 하겠습니다! 감사합니다

**Comment by ehdrb01** [comment]
구현 완료했습니다! 감사합니다.
