### ISSUE TITLE
file I/O

### ISSUE THREAD

**Issue by ehdrb01** [2023OSSL-TeamProject/MiniProject#26]
file I/O 부분에서 파일 안에 설명 부분이 추가되면 좋을 것 같습니다!

이름.   학번.   세탁기 번호
김동규 22000063 1

등의 내용으로 저장을 하고 불러오는 방식으로 진행 해보면 어떨까 싶어서 이슈 남겨드립니다!

**Comment by pangil5634** [comment]
한 번 시도해보고 결과 알려드릴게요!
