### ISSUE TITLE
최종 제출 시 유의사항

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#29]
제출기한 : 5월 22일 월요일 밤 12시 (지각시 감점있음)

* 개발이 완료된 기능을 실행하고, 실행 화면 캡쳐하여 업로드 => github repository root 위치에서 /screenshots 폴더 만들어서 이미지 업로드
* WIKI에서 완성된 함수 설명 및 결과 이미지를 이용한 페이지 추가(md 페이지 추가) 
* WIKI로 개발 자료 정리할 것
&nbsp;1. mini project 주제 및 설명
&nbsp;2. 각 함수 담당자 및 개발일정
&nbsp;3. 각 함수의 기능에 대한 간단한 설명
&nbsp;4. 그외 필요한 정보들.

**Comment by ehdrb01** [comment]
확인했습니다~!
