### ISSUE TITLE
screenshot 첨부 관련

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#31]
안녕하세요 김동규 학우님.

프로젝트를 시작한지 얼마되지 않은 것 같은데 이제 제출을 앞두고 있네요.

마지막으로 점검하는 중에 나눠야 할 부분 중에 하나인 스크린샷 관련 이슈를 남깁니다.

스크린샷을 폴더 별로 정리하고 각 기능마다 추가하는 것으로 진행하려고 하는데 어떻게 생각하시는지 궁금합니다.

**Comment by ehdrb01** [comment]
음,, 스크린샷은 그냥 하나의 파일에 몰아서 첨부하는게 어떨까요?

**Comment by pangil5634** [comment]
넵 그렇게 진행했습니다.
