### ISSUE TITLE
local Repo 생성 및 Clone 진행

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#4]
본인의 Laptop에 local Repo를 생성하시고 Clone을 진행해주세요!

진행해주신 뒤에는 댓글 부탁드립니다.

**Comment by ehdrb01** [comment]
이번 프로젝트에서 사용할 Local Repo 생성 완료 하였고, MiniProject Clone까지 완료 하였습니다.

**Comment by pangil5634** [comment]
감사합니다. 저도 Local Repo 생성하였고, Clone까지 진행했습니다.
