### ISSUE TITLE
작업 방식 - Branch에 대하여

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#5]
안녕하세요 김동규 학우님.

이번 미니프로젝트를 진행하는 부분에 있어서 가장 기본이 되고 중요한 부분인 
'작업 브랜치'에 대해서 고민해본 점을 나눠 드리려고 issue를 작성하게 되었습니다.

* 작업 tool : vscode
: 동일한 작업 tool에서 진행하는 것이 문제 발생 시 해결하는 부분에 있어서 도움될 부분이 많다고 생각합니다.
: git과 관련된 작업은 vscode의 terminal에서 진행해주시면 됩니다. (이는 conflict 수정시 보다 직관적으로 유용합니다.)

* 브랜치의 종류
1. main (default main)
2. KKI (제 브렌치)
3. KDG (동규님 브랜치)

main 브랜치의 경우 각자 merge를 진행하는 것이 아닌 합의 후 merge를 진행하려고 합니다. 각자 개발한 부분을 합치려고 할 때에 다룰 브랜치이며, 최종적으로 저희가 구현한 내용이 모여지는 브랜치입니다.

* 각자 브랜치에서의 작업 메뉴얼
1. (만약 main에서 merge가 진행된 이후에 작업 시) 각자 브랜치에서 'git pull origin main'을 진행한다. (최신 사항 update를 위함)
2. 자유롭게 작업 진행 (단, 본인의 브랜치가 맞는 지 확인한다.) - IMPORTANT
3. 커밋명은 다음과 같이 한다. ("브랜치명 : 작업 내용") - ex. git commit -m "KKI | create Delete()"
4. 본인의 브랜치에 push 한다. - ex. git push origin KKI
5. github의 repo에서 본인의 branch를 선택하여 push 내용 확인하기.

* main에서 merge 진행 시 conflict 발생 시 대처 방법
1. git merge 브랜치명
2. 터미널에서 알려주는 conflict file을 확인한다.
3. 순차적으로 충돌이 발생한 파일을 수정한다.
merge 진행 중 충돌 발생 예제

![image](https://user-images.githubusercontent.com/54162245/236400815-7f63b152-d170-40c0-b86b-

* 주의 사항
1. 작업을 진행하기 전에 어떠한 부분을 진행할 것인지에 대해서 issue를 통해서 정하면 좋겠습니다. 이는 동일한 파일을 수정함으로서 발생하는 conflict의 가능성을 줄이기 위함입니다.
2. 작업을 진행하기 전에 꼭 'branch명'을 확인해주시길 바랍니다. 본인의 작업 브랜치가 아닌 브랜치에서 진행할 경우 문제 발생 및 복잡도가 커질 것 같습니다.

* main 브랜치에서 merge 진행 방법
1. git checkout main
2. git merge 브랜치명
3. git push origin main
4. github에서 main 브랜치 확인

**Comment by pangil5634** [comment]
사진이 업로드 되지 않아서 코멘트로 남겨 드립니다,

* merge 진행 중 충돌 발생 예제
![image](https://user-images.githubusercontent.com/54162245/236400815-7f63b152-d170-40c0-b86b-0c329cbbc264.png)

**Comment by ehdrb01** [comment]
네 확인 완료했습니다! 이슈 닫아주셔도 될 것 같습니다.

**Comment by pangil5634** [comment]
backup 파일 생성에 대한 방법 안내입니다.

아래의 사진의 순서대로 진행해주시면 되며, 간결하게 정리하면 다음과 같습니다.
1. main 브랜치에서 backup하고자 하는 src폴더를 backup 폴더에 복사한다.
2. 생성된 사항을 add해주고, commit해준다. (커밋명 : 날짜 + 순서, ex:230506 1)
3. github repo로 push 해준다.
4. 자신의 브랜치로 이동하고 main 브랜치의 변경 사항을 pull 해준다.

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/54162245/236617572-0ced0bf9-26d3-4521-8678-409d891ceb39.png">
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/54162245/236617585-58d1e172-c3c0-4070-880b-26f2193f3eea.png">
