### ISSUE TITLE
기본적인 틀 구현

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#6]
안녕하세요 김동규 학우님.

저희가 구현하고자 하는 프로그램의 기본적으로 필요한 틀을 구현하고 main 브랜치에서 push했습니다.

구현한 내용은 간략하게 다음과 같습니다.

1. src, backup 폴더 생성
: src 폴더는 작업이 이루어지는 폴더이며, backup 폴더는 파일들을 백업해 놓는 폴더입니다.
2. Makefile 파일 생성
: 컴파일 과정을 보다 간편하게 진행하고자 생성했습니다.
3. main.c 파일 및 inc 폴더(각 헤더파일)
: 실행이 될 main.c 파일과 구현하고자 하는 함수들을 담고 있는 inc 폴더를 생성했습니다. CRUD.c 파일은 말 그대로 CRUD 함수들을 갖고 있으며, menu.c 파일은 CRUD를 제외한 메뉴 기능에 대한 함수를 갖고 있으며, otherFunc. 파일은 부가적으로 필요한 함수들을 갖고 있습니다.
4. .gitignore 파일 생성
: 제 작업 공간에서 생성되는 .vscode라는 폴더를 ignore 시켜면서 동시에 있으면 좋을 것 같아서 생성했습니다.

구현한 내용 확인해보시고 나누고 싶은 부분이 있다면 issue로 작성 부탁드립니다.

**Comment by ehdrb01** [comment]
감사합니다!
