### ISSUE TITLE
주제 별 필요 함수 목록

### ISSUE THREAD

**Issue by ehdrb01** [2023OSSL-TeamProject/MiniProject#8]
선정될 주제에 대한 함수를 생각해보고자 합니다!
주제 선정이 완료되면 자유롭게 함수 요구 함수 적어주시면 될 것 같습니다!

기한은 5/7(일) 오전 12시로 생각 하겠습니다!

**Comment by pangil5634** [comment]
세탁기만 다루는 것 이상으로  '세탁실 이용 시스템'으로 구축해보는 것은 어떨까요?

주된 내용은 세탁기 이용에 대한 CRUD로 진행하고, 나머지 기능은 세탁기 및 세탁실 이용에 대해서 구현해보면 좋을 것 같아요.

**Comment by ehdrb01** [comment]
네네 세탁기를 구조체로 만들어서 사용하면 될 것 같아요.

추가적으로 사용자에 대한 구조체도 하나 더 만들고 user 정보를 저장할 포인터 배열이나 Linked list를 만들면 좋을 것 같아요.

배열 말고 Linked list로 코드 작성 하는 것 어떻게 생각 하시나요?

**Comment by pangil5634** [comment]
배열이 나은거 같아요. Linked list를 사용했을 때의 장점이 있을까요? 예약 시스템에 있어서는 배열이 더 효율적인 것 같아서요.

**Comment by ehdrb01** [comment]
배열은 일단 저장이 가능한 데이터의 양이 정해지게 되어 그 부분이 큰 단점이라고 생각합니다.

예약 시스템에서 사용할 때는 상관 없을 것 같은데, 제가 말씀드린 부분은 user의 정보를 저장하는 부분이기에 array보다는 Linked list를 활용하는 부분이 조금 더 효율적이라고 생각이 듭니다!

그저 user의 정보를 저장하는 목적만 사용할 것이기에 세탁기처럼 정해진 크기가 아닌 크기의 제한을 두지 않는 부분에서 Linked list를 사용하자고 말씀드린 겁니다!

**Comment by pangil5634** [comment]
어떤 구조와 아이디어로 구현하느냐에 따라서 차이가 있겠지만, user의 정보와 세탁기의 정보를 따로 두시려는 이유가 무엇인지 궁금합니다!

어떠한 데이터를 어떤 식으로 접근해서 사용자가 입력하고 그것을 관리할 것인지에 대한 부분이 명확히 서 있어야 할 것 같네요.

**Comment by pangil5634** [comment]
**전제 조건**
* 세탁기 사용 가능 시간 : 8~22시
* 1회 이용 시간 : 1시간 (총 15회)
* 기숙사 → 층 → 세탁기 방향 순으로 접근

**기능 설명**
1. 조회 기능
: 사용자로부터 기숙사, 층, 세탁기 순으로 입력을 받아 예약하고자 하는 세탁기의 정보를 받는다.
: 이용 시간 별 사용자 정보(이름, 연락처, 호수)를 출력한다.

2. 추가 기능
: 사용자로부터 기숙사, 층, 세탁기 순으로 입력을 받아 예약하고자 하는 세탁기의 정보를 받는다.
: 이용 시간 별 사용자 정보(이름, 연락처, 호수)를 출력한다.
: 데이터를 입력 받아 저장한다. (사용자의 이름, 사용자 연락처, 사용자 방호수, 시간 준수 및 이용에 대한 책임 숙지 여부)
: 데이터 추가 성공여부를 return 한다.

3. 수정 기능
: 사용자로부터 기숙사, 층, 세탁기 순으로 입력을 받아 예약하고자 하는 세탁기의 정보를 받는다.
: 이용 시간 별 사용자 정보(이름, 연락처, 호수)를 출력한다.
: 수정하고자 하는 데이터의 번호를 입력 받는다.
: 입력 받은 데이터 번호의 유저에 대한 데이터를 다시 입력 받는다.
: 데이터 수정 성공여부를 return 한다.
: 성공 여부에 따라서 이용 금액을 차감한다.

5. 삭제 기능
: 사용자로부터 기숙사, 층, 세탁기 순으로 입력을 받아 예약하고자 하는 세탁기의 정보를 받는다.
: 이용 시간 별 사용자 정보(이름, 연락처, 호수)를 출력한다.
: 삭제하고자 하는 데이터의 번호를 입력 받는다.
: 삭제 여부를 다시 묻는다.
: 해당 데이터를 삭제한다.
: 데이터 삭제 성공여부를 return 한다.

6. 파일 저장
: 전체 데이터를 원하는 서식에 맞게 저장한다.

7. 파일 불러오기
: 불러올 txt 파일 존재 여부를 판단한다.
: 파일을 원하는 서식에 맞게 구조체 배열에 저장한다.

8. 검색 기능 (이름)
: 전체 데이터 중에서 찾을 것인지, 기숙사 내에서 찾을 것인지, 층에서 찾을 것인지 물어본다. (1, 2, 3, 4 중에서 하나)
: 사용자로부터 이름을 입력 받는다.
: 사용자가 원하는 범위 안에서 데이터를 찾아서 출력한다.

9. 유저 정보 수정하기
: 사용자의 패스워드를 수정한다.
: 사용자의 기본 정보 수정하기 (기본 값은 NULL, 이 기능이 구현되면, 추가/수정/삭제 에서도 기능 추가 가능)

10. 사용자 shop
: 세탁 카드 충전, 세제, 섬유유연제 구매

**Comment by ehdrb01** [comment]
일단 user와 세탁기의 정보 분리가 필요한 이유는 user에게 필요한 정보를 넣어주기 위함입니다.

현재 사용되는 세탁기를 생각한다면 사용자마다 세탁카드를 가지고 있고, 그 카드 내부에는 사용자마다 각기 다른 금액이 저장되어 있기 때문에 user에 정보를 따로 저장하는 것이 필요하다고 생각합니다.

**Comment by ehdrb01** [comment]
1번 조회 기능은 굳이 저렇게 구현하지 않아도 될 것 같습니다! 사용자에게 입력을 받을 필요가 없다는 생각이 듭니다.

**Comment by ehdrb01** [comment]
user에게 필요한 정보라고 하면 뭐 추가적으로 결제 정보나 이런 것들이 있을 수 있을 것 같네요!

**Comment by ehdrb01** [comment]
user에 등록되어 있지 않은 사람이라면 등록을 추가적으로 진행하면 좋을 것 같습니다.

**Comment by ehdrb01** [comment]
정리하면 user의 data에 대한 기본적인 CRUD 구현 / 세탁기에 대한 기본적인 CRUD 구현 / 파일 저장 및 불러오기 등은 필수적이고 그 외에 함수는 추가적으로 생각해볼 수 있을 것 같습니다!
