### ISSUE TITLE
WIKI, README 역할 배정

### ISSUE THREAD

**Issue by pangil5634** [2023OSSL-TeamProject/MiniProject#9]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/54162245/236612770-c357bcd3-fd83-450b-af07-2b5293f6d84c.png">

**Comment by pangil5634** [comment]
동규님 : WIKI
광일님 : README

일단 본인이 맡은 파트를 최대한 작성하는 것으로 하고, 작성해주신 이후에 서로 피드백 및 보완해주면서 점점 완성도 있게 만들어가봐요!

**Comment by ehdrb01** [comment]
네! 알겠습니다!
